# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - OUTLOOK_CLIENT_ID=${OUTLOOK_CLIENT_ID}
      - OUTLOOK_CLIENT_SECRET=${OUTLOOK_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OUTLOOK_REDIRECT_URI=${OUTLOOK_REDIRECT_URI}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SESSION_SECRET=${SESSION_SECRET}
    # depends_on:
    #   - elasticsearch

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
